# conf/model/overlap_orth.yaml
name: dr_learner
backend: sklearn            
lambda_type: none
num_crossfit: 3

nuisances:
  pi_x:  #config for estimator \pi(x)
    type: logistic
    parameters:
      penalty: l2
      C: 1.0
      tol: 1e-4
      fit_intercept: true
  pi_s_x:
    type: logistic
    parameters:
      penalty: elasticnet  #l1, l2, elasticnet
      l1_ratio: 0.5        #only used if elasticnet
      solver: saga          #saga, liblinear
      C: 1.0
      tol: 1e-4
      fit_intercept: true

  rho_x: #config for \rho(x)
    type: logistic
    parameters:
      penalty: elasticnet  #l1, l2, elasticnet
      l1_ratio: 0.5        #only used if elasticnet
      solver: saga          #saga, liblinear
      C: 1.0
      tol: 1e-4
      fit_intercept: true
  rho_s_x:
    type: logistic
    parameters:
      penalty: elasticnet  #l1, l2, elasticnet
      l1_ratio: 0.5        #only used if elasticnet
      solver: saga          #saga, liblinear
      C: 1.0
      tol: 1e-4
      fit_intercept: true
  h:     #config for h(S,X)
    type: xgboost
    crossfit: true # for orthogonal learners, f is crossfitted on obs data
    parameters:
      n_estimators: 100
      max_depth: 5
      learning_rate: 0.1
      subsample: 0.8
      colsample_bytree: 0.8
  mu_0: 
    type: xgboost # lasso, ridge, elasticnet, linear
    parameters:
      fit_intercept: False
  mu_1: 
    type: xgboost # lasso, ridge, elasticnet, linear
    parameters:
      fit_intercept: False

cate_regressor:
  type: xgboost
  parameters:
    n_estimators: 200
    max_depth: 5
    learning_rate: 0.05
    subsample: 0.8
    colsample_bytree: 0.8


  