name: RA_Learner
num_crossfit: 3

nuisances:
  h:
    type: xgboost
    crossfit: true
    parameters:
      n_estimators: 100
      max_depth: 5
      learning_rate: 0.1
      subsample: 0.8
      colsample_bytree: 0.8
  mu_0:
    type: xgboost
    parameters:
      fit_intercept: False
  mu_1:
    type: xgboost
    parameters:
      fit_intercept: False

cate_regressor:
  type: xgboost
  parameters:
    n_estimators: 100
    max_depth: 5
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
