# conf/model/overlap_orth.yaml
name: t_learner
backend: sklearn            
lambda_type: none
num_crossfit: 3

nuisances:
  h:     #config for h(S,X)
    type: xgboost
    crossfit: false # in t-learner, no need to crossfit h
    parameters:
      n_estimators: 100
      max_depth: 5
      learning_rate: 0.1
      subsample: 0.8
      colsample_bytree: 0.8
  mu_0: #config for \mu(a,x)
    type: lasso # lasso, ridge, elasticnet, linear
    parameters:
      fit_intercept: False
  mu_1: #config for \mu(a,x)
    type: lasso # lasso, ridge, elasticnet, linear
    parameters:
      fit_intercept: False
  pi_x:  #config for estimator \pi(x)
    type: logistic
    parameters:
      penalty: l2
      C: 1.0
      tol: 1e-4
      fit_intercept: true


cate_regressor:
  type: linear # lasso, ridge, elasticnet, linear
  parameters:
      fit_intercept: False


  